name: CI

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
  schedule:
    - cron: '30 2 */10 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          temp-reserve-mb: 512
          swap-size-mb: 128
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      
      - name: show
        run: df -h

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 16384
          temp-reserve-mb: 16384
          swap-size-mb: 4096

      - name: show
        run: df -h
